<script lang="ts">
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Separator } from '$lib/components/ui/separator';
	import { RECOMMENDED_TREATMENT_ID } from '$lib/config/treatment';
	import { eur, findTreatment, formatEur } from '$lib/domain';
	import ArrowRightIcon from '@lucide/svelte/icons/arrow-right';
	import CheckIcon from '@lucide/svelte/icons/check';
	import CircleCheckIcon from '@lucide/svelte/icons/circle-check';
	import { RECOMMENDATION as COPY } from './recommendation-content';

	interface Props {
		/** Questions answered, from the plan. The reference's own count is a known defect. */
		questionTotal: number;
	}

	let { questionTotal }: Props = $props();

	const treatment = findTreatment(RECOMMENDED_TREATMENT_ID);

	// Displayed, never charged: Shopify owns the amount, so this total is the sum of the
	// lines above it and nothing else depends on it.
	const total = $derived(
		eur(COPY.priceLines.reduce((sum, line) => sum + line.amount.amount, 0))
	);
</script>

<!--
	The artboard's celebration mark. Decorative: the heading below says the same thing, so it
	carries no label of its own.
-->
<div aria-hidden="true" class="flex justify-center">
	<span class="flex size-28 items-center justify-center rounded-full bg-highlight">
		<span class="flex size-20 items-center justify-center rounded-full bg-primary">
			<CheckIcon class="size-9 text-primary-foreground" />
		</span>
	</span>
</div>

<p
	class="mt-6 text-center font-sans text-xs font-semibold tracking-widest text-highlight-foreground uppercase"
>
	All {questionTotal} steps complete
</p>

<h1 class="mt-3 text-center font-display text-4xl font-medium sm:text-5xl">{COPY.headline}</h1>

<div class="mx-auto mt-4 max-w-xl text-center text-base text-muted-foreground md:text-lg">
	{#each COPY.body as line (line)}
		<p>{line}</p>
	{/each}
</div>

<ul class="mt-6 flex flex-wrap justify-center gap-2">
	{#each COPY.assurances as assurance (assurance)}
		<li>
			<Badge variant="secondary" class="gap-2 py-2">
				<CircleCheckIcon aria-hidden="true" class="size-4" />
				{assurance}
			</Badge>
		</li>
	{/each}
</ul>

{#if treatment}
	<section aria-labelledby="plan-heading" class="mt-8 rounded-lg bg-surface-warm p-6">
		<div class="flex flex-wrap items-baseline justify-between gap-2">
			<h2 id="plan-heading" class="font-display text-2xl font-medium">{treatment.name}</h2>
			<p class="text-sm text-muted-foreground">{treatment.dose} · {treatment.form}</p>
		</div>

		<dl class="mt-4 space-y-2 text-sm">
			{#each COPY.priceLines as line (line.label)}
				<div class="flex items-baseline justify-between gap-4">
					<dt class="text-muted-foreground">{line.label}</dt>
					<dd class="font-display font-semibold">{formatEur(line.amount)}</dd>
				</div>
			{/each}
			<div class="flex items-baseline justify-between gap-4">
				<dt class="text-muted-foreground">{COPY.shippingLabel}</dt>
				<dd class="font-display font-semibold">{COPY.shippingValue}</dd>
			</div>

			<Separator class="my-3" />

			<div class="flex items-baseline justify-between gap-4">
				<dt class="font-medium text-foreground">{COPY.totalLabel}</dt>
				<dd class="font-display text-xl font-semibold">{formatEur(total)}</dd>
			</div>
		</dl>

		<p class="mt-3 text-xs text-text-tertiary">{COPY.totalNote}</p>
	</section>
{/if}

<!--
	Present and inert. The checkout URL is generated by RxScale on click, which is feature 13,
	and an action that looks ready but does nothing would be worse than one that says so.
-->
<Button type="button" size="lg" class="relative mt-8 w-full" disabled>
	{COPY.action}
	<ArrowRightIcon aria-hidden="true" class="absolute right-8" />
</Button>
<p class="mt-3 text-center text-xs text-text-tertiary">
	Ordering opens once the checkout handoff is built.
</p>

<p class="mt-6 text-center text-xs text-text-tertiary">{COPY.trust.join(' · ')}</p>
